### PR TITLE
[WIP] fix conv kernel problem

### PR DESCRIPTION
**Pull request by fumihwh**
#95 
- get kernel shape in handler

If we need a kernel name list and transpose consts_protos' value before pass to `make_graph` method?
or pass dict of `consts_proto` to handler and change the values? Maybe the latter one.

### CODE REVIEW

**Comment by tjingrant** [comment]
Yeah I think something like the latter. Basically we transpose it in the conv handler and use the transposed kernel, leaving the original constant unmodified.

**Comment by fumihwh** [comment]
You mean we don't need to put transposed kernel into final graph?
Other backend will not be able to run this graph.

**Comment by tjingrant** [comment]
So the pseudo code would look like:

handle_conv:
    transpose_op = make_onnx_transpose_node( input[1], output_name="transposed_kernel" )
    conv_op = make_onnx_conv_node(input[0], "transposed_kernel")
    return [transpose_op, conv_op]

So I presume it puts the transpose operation into the final graph, but not the transposed value.

**Comment by fumihwh** [comment]
Oh, it never comes to my head.
I think change the consts directly and put transposed kernel into onnx graph (as initializer) is a better way.

**Comment by tjingrant** [comment]
OK but then you have to ensure that the weights are only used as weights, not any other purposes. (We've discussed a similar situation before). Basically you can declare a tensor, use it as the weight of a conv op and then use it somewhere else as a regular data tensor. This is unlikely but perfectly legitimate with respect to the ONNX specification. In this case you cannot change the content of the const tensor because the other operation using the tensor as a regular data tensor will be messed up.

**Comment by fumihwh** [comment]
Another way is create a copy of kernel and transpose it.
Well, it will also make things different.

**Comment by tjingrant** [comment]
I think that might work. What's your concern behind 

> Well, it will also make things different.

?

**Comment by fumihwh** [comment]
training in onnx? maybe.... although we all do not know when it comes....
size should not be a big problem, should it? (double number of weights..)

**Comment by fumihwh** [comment]
@tjingrant 
I tried the way I proposed.
Works on mnist (tf_nchw -> onnx -> caffe2).

**Pull request closed without merging**
