### PR TITLE
Implemented Opset 13 for the Greater, Identity, IsNaN, and Less operators

### PR DESCRIPTION
**Pull request by shahirdaya**
The corresponding TF operators support bfloat16 and as a result no additional test cases were added. I did add a simple test for Greater as there wasn’t one.

Greater - from Opset 9 to 13 the only change is bfloat16 support
Hardmax - from Opset 11 to 13, the default value for "axis" has been changed from "1" to "-1" and bfloat16 support has been added
Identity - from Opset 1 to 13 the only change is bfloat16 support
IsNaN - from Opset 9 to 13 the only change is bfloat16 support
Less - from Opset 9 to 13 the only change is bfloat16 support

### CODE REVIEW

**Comment by winnietsang** [comment]
@shahirdaya may you please rebase your code.

**Comment by shahirdaya** [comment]
@winnietsang I have done a rebase. Thanks

**Review by winnietsang — CHANGES_REQUESTED** [review]
@shahirdaya Hardmax Opset 13 change the default value for "axis" from "1" to "-1", and it also updated the hardmax testcases. Currently CI for this PR failed 3 of those testcases. May you please take a look. Thanks

**Comment by winnietsang** [comment]
@shahirdaya please signoff your commit

**Comment by shahirdaya** [comment]
@winnietsang I am working to figure out the issue with the Hardmax handler. Thanks

**Comment by shahirdaya** [comment]
@winnietsang @chinhuang007 as discussed, I have pulled Hardmax out of this PR as it requires a rewrite. I will tackle that in a separate PR.  This PR is ready for your review.   Thanks

**Review by winnietsang — APPROVED** [review]
LGTM

**Pull request merged**
