### PR TITLE
fix bug of different order of dict.items in python 2 and 3

### PR DESCRIPTION
**Pull request by fumihwh**

### CODE REVIEW

**Comment by tjingrant** [comment]
Why is there a bug?

**Comment by tjingrant** [comment]
Possible duplicate of https://github.com/onnx/onnx-tensorflow/issues/46 ?

**Comment by fumihwh** [comment]
For example top_k, with current code:
```
python 2.7
self.predict_net.external_output = <class 'list'>: [u'indices', u'values']
external_output = {u'indices': <tf.Tensor 'TopKV2:1' shape=(3, 3) dtype=int32>, u'values': <tf.Tensor 'TopKV2:0' shape=(3, 3) dtype=float32>}
list(external_output.values()) = <type 'list'>: [<tf.Tensor 'TopKV2:1' shape=(3, 3) dtype=int32>, <tf.Tensor 'TopKV2:0' shape=(3, 3) dtype=float32>]
list(external_output.keys()) = <type 'list'>: [u'indices', u'values']
```
```
python 3.6
self.predict_net.external_output = <class 'list'>: ['values', 'indices']
external_output = {'values': <tf.Tensor 'TopKV2:0' shape=(3, 3) dtype=float32>, 'indices': <tf.Tensor 'TopKV2:1' shape=(3, 3) dtype=int32>}
list(external_output.values()) = <class 'list'>: [<tf.Tensor 'TopKV2:0' shape=(3, 3) dtype=float32>, <tf.Tensor 'TopKV2:1' shape=(3, 3) dtype=int32>]
list(external_output.keys()) = <class 'list'>: ['values', 'indices']
```

I know after get the values, namedtupledict maps well.
But, finally, onnx side will `list` outputs from namedtupledict. It will not change the fact that order is changed.

ci error: https://travis-ci.org/onnx/onnx-tensorflow/jobs/359121776

**Comment by fumihwh** [comment]
@tjingrant BTW, they've changed way to test node. Wrapper node into model and test.

**Comment by tjingrant** [comment]
@fumihwh yes, I saw that, thanks for the heads up!

**Pull request merged**
