### PR TITLE
add max op support in frontend and fix backend

### PR DESCRIPTION
**Pull request by fumihwh**
#124

### CODE REVIEW

**Comment by tjingrant** [comment]
What seems to be the problem with the current backend?

**Comment by tjingrant** [comment]
I'm guessing problem with 1 tensor input?

**Comment by fumihwh** [comment]
@tjingrant 
Current backend works good now. But I think it is a little tricky.
Use `tf.maximum` seems more straightly and more easy to understand and maintain.
Anyway, I am ok to keep current one.

**Comment by tjingrant** [comment]
The benefit of the current implementation is that you are guaranteed, regardless of the number of input tensors, to have only 2 nodes in your computational graph. This, however, is not the case for your updated implementation and this worries me a bit.

**Comment by fumihwh** [comment]
@tjingrant 
Make sense. Reverted.

**Pull request merged**
