### PR TITLE
fix undefined shape/batch size for slice operator

### PR DESCRIPTION
**Pull request by winston-zillow**
The `slice` operator conversion failed to handle tensor shape with undefined/batch size dimension. This PR fixes it by querying the dynamic shape instead of creating a constant from static shape.

### CODE REVIEW

**Comment by winston-zillow** [comment]
@winnietsang @chinhuang007 can this one be merged?

**Comment by winston-zillow** [comment]
@chinhuang007 @winnietsang dynamic shape unit tests added

**Comment by stepelu** [comment]
Is this PR going to be ported to the `tf-1.x` branch as well?
I am getting the following error for an ONNX-exported PyTorch model for which some input dimensions (batch for instance) is not fixed using `tf-1.x` HEAD.

```
  File "/home/speluchetti/venv/t++/lib/python3.6/site-packages/onnx_tf/backend.py", line 65, in prepare
    return cls.onnx_model_to_tensorflow_rep(model, strict)
  File "/home/speluchetti/venv/t++/lib/python3.6/site-packages/onnx_tf/backend.py", line 85, in onnx_model_to_tensorflow_rep
    return cls._onnx_graph_to_tensorflow_rep(model.graph, opset_import, strict)
  File "/home/speluchetti/venv/t++/lib/python3.6/site-packages/onnx_tf/backend.py", line 143, in _onnx_graph_to_tensorflow_rep
    onnx_node, tensor_dict, handlers, opset=opset, strict=strict)
  File "/home/speluchetti/venv/t++/lib/python3.6/site-packages/onnx_tf/backend.py", line 239, in _onnx_node_to_tensorflow_op
    return handler.handle(node, tensor_dict=tensor_dict, strict=strict)
  File "/home/speluchetti/venv/t++/lib/python3.6/site-packages/onnx_tf/handlers/handler.py", line 61, in handle
    return ver_handle(node, **kwargs)
  File "/home/speluchetti/venv/t++/lib/python3.6/site-packages/onnx_tf/handlers/backend/slice.py", line 43, in version_1
    tf.constant(full_sizes)
  File "/home/speluchetti/venv/t++/lib/python3.6/site-packages/tensorflow_core/python/framework/constant_op.py", line 161, in constant_v1
    allow_broadcast=False)
  File "/home/speluchetti/venv/t++/lib/python3.6/site-packages/tensorflow_core/python/framework/constant_op.py", line 265, in _constant_impl
    allow_broadcast=allow_broadcast))
  File "/home/speluchetti/venv/t++/lib/python3.6/site-packages/tensorflow_core/python/framework/tensor_util.py", line 545, in make_tensor_proto
    "supported type." % (type(values), values))
TypeError: Failed to convert object of type <class 'list'> to Tensor. Contents: [None, 6624, None]. Consider casting elements to a supported type.
```

**Comment by winston-zillow** [comment]
@chinhuang007 please merge this PR

**Comment by winston-zillow** [comment]
@stepelu a PR is opened for tf-1.x: https://github.com/onnx/onnx-tensorflow/pull/566

**Comment by stepelu** [comment]
thanks @winston-zillow !

**Pull request merged**
