### PR TITLE
Update CI to use proper python versions

### PR DESCRIPTION
**Pull request by chinhuang007**
Made a few minor updates
1. add python version check to run different pythons in docker
2. change base OS to xenial
3. remove script for release tag so we simply run CI for master

### CODE REVIEW

**Comment by tjingrant** [comment]
Hi Chin, seeing this change:
> remove script for release tag so we simply run CI for master

I wonder how we should test release branch against onnx/tf release version?

**Comment by chinhuang007** [comment]
I believe you are talking about the test of the latest onn-tf release branch against newer onnx/tf release versions. This kind of tests should be handled separately, not during each PR push or merge. The release branch test is only needed when onnx or tf has an official new release, which happens every few months. We could add it back if we can set a trigger on ONNX an tf new releases in travis, or put it as periodic tests if we can't set such triggers. Either way I don't see the connection between a PR push/merge with release tests, therefore the remove for now.

**Comment by tjingrant** [comment]
@chinhuang007 thanks for the explaination, in this case I think it's probably okay to remove the conditional about release tests.

**Comment by chinhuang007** [comment]
Thanks for the review.

**Pull request merged**
