### PR TITLE
Use the name of onnx node as the name scope of tensorflow.

### PR DESCRIPTION
**Pull request by JiayiFu**
As we discussed in #475. When we convert a model from ONNX to Tensorflow, we always use more than one ops to implement the converting. But these ops are named with something like "Equal_27", "Less_28", "add_46" which are impossible to know what layer or op them belong to. 
So I want to add the tf.name_scope to make the generated ops more clear.
ONNX doesn't support name scope now(onnx/onnx#2444) so I use the node's name as the name scope.

### CODE REVIEW

**Comment by JiayiFu** [comment]
It seems like something wrong in the unit test env?

**Comment by JiayiFu** [comment]
@chinhuang007 May you please review this PR?

**Comment by chinhuang007** [comment]
@JiayiFu The idea of using "onnx node name" as the "tf name_scope" seems reasonable. @tjingrant What do you think? any other technical implications?

**Comment by JiayiFu** [comment]
@tjingrant Some advice?

**Comment by fumihwh** [comment]
Yes, as discussed in #475, add this sounds good.
But will it add some duplicate name? Such as 'xxx/xxx/conv/conv'?

**Comment by JiayiFu** [comment]
> Yes, as discussed in #475, add this sounds good.
> But will it add some duplicate name? Such as 'xxx/xxx/conv/conv'?

Yes, if I name an ONNX Conv node as "conv_1". Then the names of generated TensorFlow ops will be something like 'conv_1/conv'. 
But I think the names like 'conv_1/conv' are better than the names we generate now: something like 'add_16', 'conv_28' and so on. At least we can know which layer the generated ops belong to. It is more clear and easy to find the errors if there is something wrong.

**Comment by JiayiFu** [comment]
Close this. If I have any better solution I will create a new PR.

**Pull request closed without merging**
