### PR TITLE
Add Greater v9

### PR DESCRIPTION
**Pull request by chinhuang007**
Add Greater v9 support. No changes seem needed, just to
declare support of v9.

### CODE REVIEW

**Comment by tjingrant** [comment]
@chinhuang007 it seems like they relaxed type constraints for a bunch of other ops including gemm, flatten, etc. c.f. https://travis-ci.org/onnx/onnx-tensorflow/jobs/436798995

Maybe we should just take care of them all at once here..

**Comment by chinhuang007** [comment]
Yeah, a few operators got support for additional types. Sure,b I will add others.

**Comment by tjingrant** [comment]
@ibm-jenkins test this please.

**Comment by fumihwh** [comment]
@chinhuang007 Could you add `Less` also?

**Comment by chinhuang007** [comment]
@fumihwh Less was already covered before this PR.

**Pull request merged**
