### PR TITLE
tiny refactoring

### PR DESCRIPTION
**Pull request by fumihwh**
In case that multiple tf ops match same onnx op.

### CODE REVIEW

**Comment by tjingrant** [comment]
I feel like this one-to-one condition is something that should be preserved (for error prevention). I think you want to loose this one-to-one check b/c of BiasAdd right? In that case, a special handler for BiasAdd is more appropriate as per this post: https://stackoverflow.com/questions/43131606/whats-the-difference-of-add-methods-in-tensorflow

**Comment by fumihwh** [comment]
Yes, I add `to_list` attr for same reason as you said to make it explicitly.
A special handler for `BiasAdd` makes more sense, but in frontend, do we need to check dtype?
Of course `BiasAdd` is just a example, so the problem is how to define which op should use special handler, which op could mapping directly.

**Comment by tjingrant** [comment]
@fumihwh my take is that in the onnx->tensorflow direction we'll just use add because BiasAdd is baked into the handle_conv handler of the backend. And in tensorflow->onnx direction they are naturally handled different b/c Add has a trivial handler and BiasAdd has a special handler. The problem with the proposed change in common.py is that now we cannot detect unexpected many-to-one mapping in the future in `TF_OP_STR_TO_ONNX_OP`, which should never happen (except for very rare cases like this).

I think BiasAdd is a very rare exception and we should not change the current error prevention mechanism just for this single exception.

**Comment by fumihwh** [comment]
@tjingrant OK～Let's remove that part.

**Pull request merged**
