### PR TITLE
[WIP] add lstm handler

### PR DESCRIPTION
**Pull request by fumihwh**
I've added lstm handler. But without `reverse` direction support. I don't know how to do that. Any ideas?

### CODE REVIEW

**Comment by tjingrant** [comment]
I'm as clueless as you are. I thought only forward / bidirectional makes sense.
The best way to resolve this is maybe to raise an issue in the ONNX spec issue page.

**Comment by tjingrant** [comment]
This patch looks good otherwise, maybe just rebase and merge for now?

**Comment by fumihwh** [comment]
@tjingrant 
Sure. But should we add a TODO to it?

**Comment by fumihwh** [comment]
@tjingrant 
```
    elif direction == "reverse":
      def _reverse(input_, seq_dim):
        return array_ops.reverse(input_, axis=[seq_dim])
      time_dim = 0
      inputs_reverse = _reverse(input_dict[node.inputs[0]], time_dim)
      output, state = tf.nn.dynamic_rnn(cell,
                                        inputs_reverse,
                                        time_major=True,
                                        dtype=tf.float32)
```
I read the `bidirectional_dynamic_rnn` [source](https://github.com/tensorflow/tensorflow/blob/r1.6/tensorflow/python/ops/rnn.py#L324-L451) and have found `reverse` part.
Tried to add a if branch into handler. What do you think?

**Comment by tjingrant** [comment]
@fumihwh sounds good.

**Comment by tjingrant** [comment]
@fumihwh thanks a lot!!

**Pull request merged**
