### PR TITLE
support some ops and add default attr value injection

### PR DESCRIPTION
**Pull request by fumihwh**
- ReduceL1
- ReduceSumSquare

### CODE REVIEW

**Comment by tjingrant** [comment]
@fumihwh why is specialized handlers needed here?
These ops seem to have already been covered here (https://github.com/onnx/onnx-tensorflow/blob/465a02819ebff33ee014ebed17a1b70f66310fcb/onnx_tf/common.py#L117).

**Comment by fumihwh** [comment]
@tjingrant My fault. I will revert there parts.

**Comment by tjingrant** [comment]
Then it looks more like we need the ability to set default attribute rather than there's a need for re-implementing all these operations?

Optimally we should have as many ops automatically handled as possible. What do you think?

**Comment by fumihwh** [comment]
@tjingrant 
BTW, currently I put `DEFAULT_ONNX_ATTR_PER_OP ` in `common.py`. Is it better to put it just in `backend.py`?

**Comment by tjingrant** [comment]
@fumihwh yeah I think moving it into `backend.py` is probably a good idea. Moreoever, why is handle_reduce_sum_square not automatically handled?

**Comment by fumihwh** [comment]
@tjingrant 
I can’t find corresponding op in tensorflow.

**Comment by tjingrant** [comment]
@fumihwh Oh I see.... sorry I missed that.

**Pull request merged**
